const app=document.querySelector('#app'), content=document.querySelector('#content'), status=document.querySelector('#status');
const post=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
let entities=[]; const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function scene(){content.innerHTML=`<div class="form">${entities.length?entities.map(e=>`<div class="row"><span>${esc(e.name)}<small> · ${e.type}</small></span><span><button data-clone="${e.id}">Clone</button><button data-delete="${e.id}">Delete</button></span></div>`).join(''):'<p>No actors, props or vehicles.</p>'}</div>`}
function spawn(){content.innerHTML=`<div class="form"><label>Type<select id="type"><option value="actor">Actor</option><option value="prop">Prop</option><option value="vehicle">Vehicle</option></select></label><label>Model<input id="model" placeholder="e.g. a_m_m_business_01"></label><label>Name<input id="name" placeholder="Optional label"></label><button class="accent" id="spawn">Spawn entity</button></div>`;document.querySelector('#spawn').onclick=async()=>{let r=await post('spawn',{type:type.value,model:model.value,name:name.value});if(r.ok){entities.push(r.result);scene()}else status.textContent='Spawn failed'}}
function animation(){content.innerHTML=`<div class="form"><p>Choose an actor in Scene, then use a known GTA animation dictionary and clip.</p><label>Dictionary<input id="dict" placeholder="amb@world_human_cheering@male_a"></label><label>Clip<input id="clip" placeholder="base"></label><button id="preview">Preview on player</button></div>`;preview.onclick=()=>post('previewAnimation',{animation:{dict:dict.value,name:clip.value,loop:true}})}
function weather(){content.innerHTML=`<div class="form"><label>Weather<select id="w"><option>CLEAR</option><option>FOGGY</option><option>RAIN</option><option>CLOUDS</option></select></label><label>Hour<input id="hour" type="number" min="0" max="23" value="12"></label><button id="apply" class="accent">Apply atmosphere</button></div>`;apply.onclick=()=>post('weather',{weather:w.value,hour:+hour.value,minute:0})}
function render(tab='entities'){({entities:scene,spawn,animation,weather})[tab]()} render();
document.addEventListener('click',async e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.tab){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.tab)}if(b.dataset.delete){await post('delete',{id:b.dataset.delete});entities=entities.filter(x=>x.id!==b.dataset.delete);scene()}if(b.dataset.clone){let r=await post('clone',{id:b.dataset.clone});if(r.ok){entities.push(r.result);scene()}}let a=b.dataset.action;if(a==='close')post('close');if(a==='save')post('save',{name:project.value});if(a==='camera')post('camera',{action:'toggle'});if(a==='undo'||a==='redo')post(a);if(a==='load')status.textContent='Use a project id from your project listing integration.'});
addEventListener('message',e=>{let d=e.data;if(d.action==='open'){app.classList.add('open');project.value=d.project?.name||'Untitled Scene';entities=d.entities||[];render()}if(d.action==='close')app.classList.remove('open');if(d.action==='saved')status.textContent=`Saved #${d.id}`});
document.addEventListener('keydown',e=>{if(e.key==='Escape')post('close');if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();post('save',{name:project.value})}if(e.ctrlKey&&e.key.toLowerCase()==='z')post(e.shiftKey?'redo':'undo')});
