const state={project:{id:null,name:'Untitled Scene'},entities:[],section:'dashboard',selected:null,playing:false};
const $=(q,r=document)=>r.querySelector(q);const $$=(q,r=document)=>[...r.querySelectorAll(q)];
const nui=(event,data={})=>fetch(`https://${GetParentResourceName()}/${event}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json());
const icon={actor:'fa-user',prop:'fa-cube',vehicle:'fa-car-side'};
function status(message,type='ok'){const el=$('#status-message');el.innerHTML=`<i class="fa-solid ${type==='error'?'fa-triangle-exclamation':'fa-circle-check'}"></i> ${message}`;}
function inspector(){const content=$('#inspector-content'),title=$('#inspector-title');if(!state.selected){title.textContent='Scene properties';content.innerHTML='<p class="empty-inspector">Select an actor, prop, vehicle, camera, or weather control to reveal its properties.</p>';return}title.textContent=state.selected.name;content.innerHTML=`<section class="field-group"><h3>Transform</h3>${[['X',0],['Y',0],['Z',0],['Heading',0]].map(([l,v])=>`<div class="field"><label>${l}</label><input type="range" min="-1000" max="1000" value="${v}"><output>${v.toFixed(2)}</output></div>`).join('')}</section><section class="field-group"><h3>Selection</h3><div class="field"><label>Type</label><output>${state.selected.type}</output></div><div class="field"><label>Model</label><output>${state.selected.model}</output></div></section>`;}
function entities(){const host=$('#viewport-content');host.querySelectorAll('.entity-card').forEach(x=>x.remove());if(!state.entities.length)return;$('.viewport-empty',host)?.remove();state.entities.forEach(entity=>{const node=$('#entity-template').content.firstElementChild.cloneNode(true);$('.entity-icon',node).innerHTML=`<i class="fa-solid ${icon[entity.type]||'fa-cube'}"></i>`;$('strong',node).textContent=entity.name;$('small',node).textContent=entity.type;node.onclick=e=>{if(e.target.closest('.entity-delete'))return;state.selected=entity;$('#selection-label').textContent=entity.name;inspector();};$('.entity-delete',node).onclick=async()=>{await nui('delete',{id:entity.id});state.entities=state.entities.filter(x=>x.id!==entity.id);state.selected=null;entities();inspector();status(`${entity.name} removed`)};host.append(node);});}
function section(name){state.section=name;const labels={dashboard:['DASHBOARD','Scene viewport'],projects:['PROJECTS','Project library'],scenes:['SCENES','Scene builder'],actors:['ACTORS','Actor casting'],props:['PROPS','Prop placement'],vehicles:['VEHICLES','Vehicle staging'],cameras:['CAMERAS','Camera rig'],animations:['ANIMATIONS','Performance library'],weather:['WEATHER','Atmosphere'],settings:['SETTINGS','Director preferences']};const [kicker,title]=labels[name];$('#section-kicker').textContent=kicker;$('#workspace-title').textContent=title;$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.section===name));if(['actors','props','vehicles'].includes(name))status(`Choose a ${name.slice(0,-1)} model and spawn it from the director library`);}
async function projects(){const result=await nui('projects');if(!result.ok){status('Project listing unavailable','error');return}const select=$('#project-select');select.innerHTML=(result.result||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')||'<option>Untitled Scene</option>';status(`${(result.result||[]).length} projects available`);}
async function action(name){if(name==='close')return nui('close');if(name==='save'){const result=await nui('save',{name:state.project.name});return status(result.ok?'Project saved':'Save failed',result.ok?'ok':'error')}if(name==='undo'||name==='redo'){await nui(name);return status(`${name[0].toUpperCase()+name.slice(1)} requested`)}if(name==='camera'){await nui('camera',{action:'toggle'});$('#camera-state').textContent=$('#camera-state').textContent==='Freecam'?'Gameplay camera':'Freecam';return}if(name==='play'){state.playing=!state.playing;$('.play-button i').className=`fa-solid fa-${state.playing?'pause':'play'}`;return status(state.playing?'Timeline playing':'Timeline paused')}if(name==='export'){const result=await nui('export');if(!result.ok)return status('Export failed','error');const blob=new Blob([JSON.stringify(result.result,null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`${result.result.name||'scene'}.json`;link.click();URL.revokeObjectURL(link.href);return status('Project exported')}if(name==='import'){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{const file=input.files[0];if(!file)return;try{const result=await nui('import',JSON.parse(await file.text()));if(!result.ok)throw Error();state.project.name=result.result.name;state.entities=result.result.entities;entities();inspector();status('Project imported')}catch{status('Invalid project file','error')}};input.click();return}}
$$('[data-section]').forEach(b=>b.addEventListener('click',()=>section(b.dataset.section)));document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action)});$('#global-search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$$('.nav-item').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(q));});document.addEventListener('keydown',e=>{if(e.key==='Escape')nui('close');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();action('save')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();action(e.shiftKey?'redo':'undo')}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#global-search').focus()}});
addEventListener('message',e=>{const data=e.data||{};if(data.action==='open'){state.project=data.project||state.project;state.entities=data.entities||[];$('#director').classList.add('open');$('#project-select').innerHTML=`<option>${state.project.name||'Untitled Scene'}</option>`;$('#timeline-name').textContent=`${state.project.name||'Untitled Scene'} · 00:30`;entities();inspector();projects()}if(data.action==='close')$('#director').classList.remove('open');if(data.action==='saved'){$('#autosave-state').textContent='Saved';status(`Project #${data.id} saved`)}});
setInterval(()=>{$('#fps').textContent=String(Math.round(58+Math.random()*4));},1000);
