--- oxmysql adapter. Every query uses bound parameters; unavailable storage fails closed.
SpectremDirector.Database = {}
local D=SpectremDirector.Database
local function valid(name) assert(type(name)=='string' and name:match('^[a-z_]+$'),'unsafe SQL identifier') end
local function condition(filters, values) local clauses={}; for key,value in pairs(filters) do valid(key); clauses[#clauses+1]='`'..key..'`=?'; values[#values+1]=value end; assert(#clauses>0,'filter required'); return table.concat(clauses,' AND ') end
function D.available() return SpectremDirector.Features.mysql==true end
function D.create(tableName, data) if not D.available() then return nil,'database disabled' end; valid(tableName); local keys,values,marks={}, {}, {}; for key,value in pairs(data) do valid(key); keys[#keys+1]='`'..key..'`';values[#values+1]=value;marks[#marks+1]='?' end; local ok,result=pcall(MySQL.insert.await,('INSERT INTO `%s` (%s) VALUES (%s)'):format(tableName,table.concat(keys,','),table.concat(marks,',')),values); return ok and result or nil,result end
function D.find(tableName, filters) if not D.available() then return nil,'database disabled' end; valid(tableName); local values={}; local ok,result=pcall(MySQL.single.await,('SELECT * FROM `%s` WHERE %s LIMIT 1'):format(tableName,condition(filters,values)),values); return ok and result or nil,result end
function D.all(tableName, filters) if not D.available() then return {},'database disabled' end; valid(tableName); local values={}; local query='SELECT * FROM `'..tableName..'`'; if filters then query=query..' WHERE '..condition(filters,values) end; local ok,result=pcall(MySQL.query.await,query,values); return ok and result or {},result end
function D.update(tableName, data, filters) if not D.available() then return nil,'database disabled' end; valid(tableName); local set,values={},{}; for key,value in pairs(data) do valid(key);set[#set+1]='`'..key..'`=?';values[#values+1]=value end; local ok,result=pcall(MySQL.update.await,('UPDATE `%s` SET %s WHERE %s'):format(tableName,table.concat(set,','),condition(filters,values)),values); return ok and result or nil,result end
function D.delete(tableName, filters) if not D.available() then return nil,'database disabled' end; valid(tableName); local values={}; local ok,result=pcall(MySQL.update.await,('DELETE FROM `%s` WHERE %s'):format(tableName,condition(filters,values)),values); return ok and result or nil,result end
function D.transaction(statements) if not D.available() then return false,'database disabled' end; local ok,result=pcall(MySQL.transaction.await,statements); return ok and result or false,result end
